[features]
seeds = false
skip-lint = false

[programs.localnet]
neutralalpha_vault = "Fg6PaFpoGXkYsidMpWxTWqkZ6rN1Y2fYgR6K9YqR9Qj3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
